apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ray-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ray-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ray-worker
    spec:
      restartPolicy: Always
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: ray-worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["/bin/bash", "-c", "--"]
        args:
          # This address now points to the stable DNS name of the StatefulSet pod.
          - "ray start --num-cpus=$MY_CPU_REQUEST --address=ray-head-svc:6380 --object-manager-port=8076 --node-manager-port=8077 --dashboard-agent-grpc-port=8078 --dashboard-agent-listen-port=52365 --min-worker-port=10002 --max-worker-port=10020 --block"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: MY_CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                resource: requests.cpu
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
